name: Pack

on:
  push:
    branches:
      - 'mc*.*.*'
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/upload-artifact@v3
        with:
          name: ${{github.ref_name}}
          path: src
